// Code generated by "stringer -type=BaseType"; DO NOT EDIT

package gli

import "fmt"

const _BaseType_name = "BaseTypeFloatBaseTypeIntBaseTypeUnsignedIntBaseTypeBool"

var _BaseType_index = [...]uint8{0, 13, 24, 43, 55}

func (i BaseType) String() string {
	i -= 1
	if i >= BaseType(len(_BaseType_index)-1) {
		return fmt.Sprintf("BaseType(%d)", i+1)
	}
	return _BaseType_name[_BaseType_index[i]:_BaseType_index[i+1]]
}
