// Code generated by "stringer -type=BufferUsage"; DO NOT EDIT

package gli

import "fmt"

const _BufferUsage_name = "BufferUsageStreamDrawBufferUsageStreamReadBufferUsageStreamCopyBufferUsageStaticDrawBufferUsageStaticReadBufferUsageStaticCopyBufferUsageDynamicDrawBufferUsageDynamicReadBufferUsageDynamicCopy"

var _BufferUsage_index = [...]uint8{0, 21, 42, 63, 84, 105, 126, 148, 170, 192}

func (i BufferUsage) String() string {
	i -= 1
	if i >= BufferUsage(len(_BufferUsage_index)-1) {
		return fmt.Sprintf("BufferUsage(%d)", i+1)
	}
	return _BufferUsage_name[_BufferUsage_index[i]:_BufferUsage_index[i+1]]
}
