// Code generated by "stringer -type=BufferTarget"; DO NOT EDIT

package gli

import "fmt"

const _BufferTarget_name = "BufferTargetArrayBufferTargetCopyReadBufferTargetCopyWriteBufferTargetElementArrayBufferTargetPixelPackBufferTargetPixelUnpackBufferTargetTextureBufferTargetTransformFeedbackBufferTargetUniform"

var _BufferTarget_index = [...]uint8{0, 17, 37, 58, 82, 103, 126, 145, 174, 193}

func (i BufferTarget) String() string {
	i -= 1
	if i >= BufferTarget(len(_BufferTarget_index)-1) {
		return fmt.Sprintf("BufferTarget(%d)", i+1)
	}
	return _BufferTarget_name[_BufferTarget_index[i]:_BufferTarget_index[i+1]]
}
