// Code generated by "stringer -type=ResourceType"; DO NOT EDIT

package gli

import "fmt"

const _ResourceType_name = "ResourceTypeUniformResourceTypeAttribute"

var _ResourceType_index = [...]uint8{0, 19, 40}

func (i ResourceType) String() string {
	i -= 1
	if i >= ResourceType(len(_ResourceType_index)-1) {
		return fmt.Sprintf("ResourceType(%d)", i+1)
	}
	return _ResourceType_name[_ResourceType_index[i]:_ResourceType_index[i+1]]
}
