// Code generated by "stringer -type=SamplerType"; DO NOT EDIT

package gli

import "fmt"

const _SamplerType_name = "SamplerType1dSamplerType2dSamplerType3dSamplerTypeCudeSamplerType2dRectSamplerType1dArraySamplerType2dArraySamplerTypeCubeArraySamplerTypeBufferSamplerType2dMSSamplerType2dMSArraySamplerType1dShadowSamplerType2dShadowSamplerTypeCubeShadowSamplerType2dRectShadowSamplerType1dArrayShadowSamplerType2dArrayShadowSamplerTypeCubeArrayShadow"

var _SamplerType_index = [...]uint16{0, 13, 26, 39, 54, 71, 89, 107, 127, 144, 159, 179, 198, 217, 238, 261, 285, 309, 335}

func (i SamplerType) String() string {
	i -= 1
	if i >= SamplerType(len(_SamplerType_index)-1) {
		return fmt.Sprintf("SamplerType(%d)", i+1)
	}
	return _SamplerType_name[_SamplerType_index[i]:_SamplerType_index[i+1]]
}
